name: Deploy Application

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Show selected environment
        run: |
          echo "Selected environment: ${{ inputs.environment }}"

      - name: Deploy
        run: |
          echo "Deploying application to ${{ inputs.environment }}"
